name: CI/CD Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with: Log in to GitHub Container Registry
          registry: ghcr.iov2
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}io
 }}
      - name: Build and Push Docker image          password: ${{ secrets.GHCR_PAT }}
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/square-ml-demo:latest .image
          docker push ghcr.io/${{ github.repository_owner }}/square-ml-demo:latest|
 docker build \
      - name: Set up kubectl_CACHE=1 \
        uses: azure/setup-kubectl@v3.repository_owner }}/square-ml-demo:latest \
        with:            --tag ghcr.io/${{ github.repository_owner }}/square-ml-demo:latest .
          version: 'v1.25.0'repository_owner }}/square-ml-demo:latest

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config

      - name: Deploy MetalLBconfig
        run: |
          kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yamlir -p $HOME/.kube  # Ensure the .kube directory exists
          sleep 30KUBE_CONFIG_DATA }}" > $HOME/.kube/config
          cat <<EOF > metallb-config.yaml
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:b/metallb/v0.13.10/config/manifests/metallb-native.yaml
            namespace: metallb-system
            name: default-address-pool          cat <<EOF > metallb-config.yaml
          spec:b.io/v1beta1
            addresses:: IPAddressPool
            - ${{ secrets.METALLB_IP_RANGE }}
          ---ace: metallb-system
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            namespace: metallb-systemecrets.METALLB_IP_RANGE }}
            name: default
          EOFa1
          kubectl apply -f metallb-config.yaml L2Advertisement

      - name: Deploy Application to Kubernetes
        run: |ame: default
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yamlllb-config.yaml

      - name: Get Service External IPubernetes
        run: |
          kubectl get svc square-ml-demo