---
name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            -t ghcr.io/${{ github.repository_owner }}/square-ml-demo:latest .

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.0'

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the .kube directory exists
          echo "${{ secrets.KUBE_CONFIG_DATA }}" > $HOME/.kube/config.kube/config
          chmod 600 $HOME/.kube/config  # Secure the kubeconfig file

      - name: Debug Kubeconfig
        run: |
          echo "Kubeconfig being used:"
          cat $HOME/.kube/config

      - name: Debug Kubeconfig
        run: |
          echo "Decoded kubeconfig:"
          cat $HOME/.kube/config

      - name: Test Kubernetes Connection
        run: |
          echo "Testing Kubernetes connection..."
          kubectl version
          kubectl get nodes

      - name: Debug Kubernetes Connection
        run: |
          kubectl config view
          kubectl get nodes

      - name: Deploy MetalLB
        run: |
          kubectl apply -f \
            https://raw.githubusercontent.com/metallb/metallb/v0.13.10/config/manifests/metallb-native.yaml
          sleep 30
          cat <<EOF > metallb-config.yaml
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            namespace: metallb-system
            name: default-address-pool
          spec:
            addresses:
            - ${{ secrets.METALLB_IP_RANGE }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            namespace: metallb-system
            name: default
          EOF
          kubectl apply -f metallb-config.yaml

      - name: Deploy Application to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Get Service External IP
        run: |
          kubectl get svc square-ml-demo
